In [3]:
import numpy as np

# I. numpy array cơ bản

1. Tạp array


In [ ]:
a = np.array([1, 2, 3, 4, 5])

In [ ]:
b = np.array([[1,2,3],[4,5,6]])

In [ ]:
zeros =   np.zeros(5)

In [ ]:
ones = np.ones((2, 3))

2. Các hàm tạo array tiện lợi

In [ ]:
r = np.arange(0, 10, 3)
print(r)

[0 3 6 9]


In [ ]:
lin = np.linspace(0, 1,5)
print(lin)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
nhiet_do = np.array([28.5, 30.1, 29.8, 31.2, 27.6, 26.9, 28.0])
print(nhiet_do)

[28.5 30.1 29.8 31.2 27.6 26.9 28. ]


In [ ]:
diem = np.array([[6,7, 8], [7,8,7], [10, 8, 3]])
print(diem)

[[ 6  7  8]
 [ 7  8  7]
 [10  8  3]]


In [ ]:
e = np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


3. Shape — hình dạng của mảng

In [ ]:
arr = np.arange(12)
arr.reshape(3, 4)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


4. Dtype — kiểu dữ liệu

In [ ]:
arr = np.array([[1.0, 2.5, 3.1],
                [4.8, 5.0, 6.2]])
print(arr.nbytes)

48


5. Thuộc tính quan trọng nhất

In [ ]:
arr = np.array([[1.0, 2.5, 3.1],
                [4.8, 5.0, 6.2]])

arr.shape   # → (2, 3)  — 2 hàng, 3 cột
arr.ndim    # → 2      — số chiều
arr.size    # → 6      — tổng số phần tử
arr.dtype   # → float64 — kiểu dữ liệu
arr.nbytes  # → 48     — bộ nhớ (bytes)

#II. numpy indexing và slicing

Dataset mẫu — điểm thi của 5 học sinh (4 môn)

In [ ]:
# Hàng = học sinh, Cột = [Toán, Lý, Hóa, Văn]
scores = np.array([
    [85, 72, 90, 78],   # HS 0: An
    [60, 55, 62, 70],   # HS 1: Bình
    [95, 88, 91, 85],   # HS 2: Châu
    [45, 50, 48, 55],   # HS 3: Dũng
    [78, 82, 74, 80],   # HS 4: Em
])

In [ ]:
print(scores)

[[85 72 90 78]
 [60 55 62 70]
 [95 88 91 85]
 [45 50 48 55]
 [78 82 74 80]]


In [ ]:
# Lấy điểm Toán của tất cả học sinh (cột 0)
toan = scores[:, 0]
print(toan)

[999  60  95  45  78]


In [ ]:
# Lấy điểm của HS 2 (Châu) — tất cả môn
chau = scores[2]
print(chau)

[95 88 91 85]


In [ ]:
# Phần tử cuối cùng — index âm
print(scores[-1, -1])

80


In [ ]:
# Slicing tạo VIEW — thay đổi ảnh hưởng array gốc
sub = scores[0:2, :]
sub[0, 0] = 999   # scores bị thay đổi theo
print(scores)

[[999  72  90  78]
 [ 60  55  62  70]
 [ 95  88  91  85]
 [ 45  50  48  55]
 [ 78  82  74  80]]


In [ ]:
# Fancy indexing tạo COPY — an toàn hơn
sub = scores[[0, 1], :]
sub[0, 0] = 999        # scores không bị ảnh hưởng

# III. Broadcasting trong numpy

1. Cộng một số vào mọi phần tử — đây là broadcasting đơn giản nhất. Scalar được "kéo giãn" thành ma trận cùng shape.

In [ ]:
prices = np.array([[10, 20, 30],
                [15, 25, 35]])
tax = 5
result = prices + tax
print(result)

[[15 25 35]
 [20 30 40]]


2. Trừ trung bình từng cột — thao tác chuẩn hóa dữ liệu. Vector (3,) được broadcast theo chiều hàng.

In [ ]:
data = np.array ([[1, 2, 3], [4,5,6], [7,8,9]])
col = [5 ,8 , 7]
temp = data - col
print(temp)

[[-4 -6 -4]
 [-1 -3 -1]
 [ 2  0  2]]


3. Nhân vector cột (3,1) với vector hàng (1,4) — tạo ra bảng tổ hợp (outer product). Cực kỳ hay dùng trong ML.

In [ ]:
rows = np.array([[1],[2],[3]])
col = np.array([10, 20, 30, 40])

print(rows * col)

[[ 10  20  30  40]
 [ 20  40  60  80]
 [ 30  60  90 120]]


4. Khi hai chiều khác nhau và không có chiều nào bằng 1 — NumPy báo lỗi. Không thể kéo giãn.

In [ ]:
A = np.array([[1, 2, 3],
               [4, 5, 6]])
B = np.array([[10, 20],
               [30, 40]])
print(A + B)

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [ ]:
A = np.array([[1, 2, 3],
               [4, 5, 6]])
B = np.array([[10, 20, 30],
               [30, 40, 50]]) # Modified B to have shape (2,3) for compatibility
print(A + B)

[[11 22 33]
 [34 45 56]]


#IV. Các hàm toán học trong numpy

In [5]:
scores = np.array([
    [85, 72, 90, 78],  # An
    [60, 55, 62, 70],  # Bình
    [95, 88, 91, 85],  # Châu
    [45, 50, 48, 55],  # Dũng
    [78, 82, 74, 80],  # Em
])  # shape: (5, 4)

1. Sum (tổng)

In [ ]:
print (np.sum(scores))

1443


2. Mean (trung bình toàn bộ)

In [ ]:
print (np.mean(scores))

72.15


3. std (Độ lệch chuẩn)

In [ ]:
print(np.std(scores))

15.268513352648318


4. Min (Điểm thấp nhất)

In [ ]:
np.min(scores)

np.int64(45)

5. Max (Điểm cao nhất)

In [6]:
print(np.max(scores))

95


6. Median (Điểm trung bình từng học sinh vs từng môn)

**note**: axis=0 nghĩa là "sụp theo chiều hàng" → kết quả là 1 hàng (thống kê theo cột).
axis=1 nghĩa là "sụp theo chiều cột" → kết quả là 1 cột (thống kê theo hàng)

In [ ]:
# Điểm trung bình từng học sinh
avg_student = np.mean(scores, axis=1)
# Điểm trung bình từng môn
avg_subject = np.mean(scores, axis=0)

In [ ]:
# Chuẩn hóa dữ liệu trước khi đưa vào model
mu  = np.mean(X, axis=0)   # trung bình từng feature
sig = np.std(X, axis=0)    # std từng feature
Z   = (X - mu) / sig       # Z-score, shape giữ nguyên

7. np.linalg — 4 hàm hay dùng nhất trong ML

*  scores @ W hoặc np.dot(): Nhân ma trận — forward pass của neural net
*  np.linalg.norm(v): Tính khoảng cách, chuẩn hóa vector
* np.linalg.eig(C): PCA — tìm chiều dữ liệu quan trọng nhất
* np.corrcoef(X.T): Khám phá tương quan giữa các feature



#V.  Reshape, stack, concatenate, split trong numpy

1. Reshape — đổi hình, giữ nguyên dữ liệu

In [ ]:
pixels = np.arange(1, 13)          # shape (12,)  ← ảnh flatten
img    = pixels.reshape(3, 4)       # shape (3,4)  ← ảnh 3×4
img_t  = pixels.reshape(4, 3)       # shape (4,3)
flat   = img.reshape(-1)            # shape (12,)  ← -1 tự tính
batch  = pixels.reshape(1, -1)      # shape (1,12) ← thêm batch dim

# Ứng dụng CNN: (samples, H, W) → (samples, H*W)
X = np.random.randn(100, 28, 28)    # 100 ảnh MNIST
X_flat = X.reshape(100, -1)         # (100, 784)

######Tránh bẫy hay gặp:

In [ ]:
# Đừng build array bằng vòng lặp như này
result = np.array([])
for x in data:
    result = np.append(result, process(x))   # chậm kinh khủng! O(n²)

# Làm đúng: dùng list, convert một lần cuối
result = [process(x) for x in data]
result = np.array(result)                    # nhanh hơn hàng trăm lần

# VII. Numpy random

**numpy.random** là công cụ không thể thiếu — dùng để tạo dữ liệu test, khởi tạo model, mô phỏng thống kê, và chia train/test.

**1. Seed — tái lập kết quả**

Seed là "chìa khóa" của bộ sinh số ngẫu nhiên. Cùng seed → cùng kết quả. Bắt buộc trong nghiên cứu và debug.

In [ ]:
# Không seed — mỗi lần chạy ra số khác
np.random.randn(3)   # [0.47, -1.23, 0.89] (ví dụ)
np.random.randn(3)   # [-0.12, 2.01, 0.33] (khác!)

# Có seed — luôn ra cùng kết quả
np.random.seed(42)
np.random.randn(3)   # [0.494, -0.138, 0.647]
np.random.seed(42)
np.random.randn(3)   # [0.494, -0.138, 0.647]  ← SAME

# Best practice: dùng Generator mới hơn
rng = np.random.default_rng(seed=42)
rng.standard_normal(3)

**2. Phân phối chuẩn**

Xuất hiện ở khắp nơi: điểm thi, chiều cao, sai số đo lường, khởi tạo weight neural network.



In [ ]:
rng = np.random.default_rng(42)

# Chuẩn hóa (mean=0, std=1)
z = rng.standard_normal(1000)

# Tùy chỉnh mean và std
heights = rng.normal(loc=170, scale=8, size=1000)
# loc=mean, scale=std

# 2D — ma trận ngẫu nhiên
W = rng.normal(0, 0.01, size=(128, 64))  # init weights

# Quy tắc 68-95-99.7
# 68% nằm trong [mean-std, mean+std]
# 95% nằm trong [mean-2std, mean+2std]
# 99.7% nằm trong [mean-3std, mean+3std]

**3. Các phân phối khác**

Mỗi phân phối mô hình hóa một loại hiện tượng khác nhau. Chọn đúng phân phối = mô hình tốt hơn.

In [ ]:
rng = np.random.default_rng(42)

# Uniform — giá trị đều nhau trong [low, high]
prices = rng.uniform(100, 500, 1000)     # giá sản phẩm

# Binomial — n lần thử, xác suất p mỗi lần
clicks = rng.binomial(n=1000, p=0.03, size=500)  # CTR

# Poisson — số sự kiện trong khoảng thời gian
orders = rng.poisson(lam=15, size=365)   # đơn/ngày

# Exponential — thời gian giữa 2 sự kiện
wait   = rng.exponential(scale=5, size=1000)  # phút chờ

# Beta — xác suất, tỉ lệ ∈ [0,1]
conv   = rng.beta(a=2, b=8, size=1000)  # tỉ lệ chuyển đổi

**4. Shuffle & sampling**

Trộn và lấy mẫu — dùng mỗi khi chia train/test, tạo mini-batch, bootstrap.

In [ ]:
rng = np.random.default_rng(42)
data = np.arange(10)   # [0..9]

# Trộn ngẫu nhiên (in-place)
rng.shuffle(data)
# → [7, 2, 5, 0, 3, 9, 1, 8, 4, 6]

# Chọn k phần tử không lặp (không hoàn lại)
rng.choice(data, size=3, replace=False)
# → [7, 2, 5]

# Chọn có lặp (bootstrap)
rng.choice(data, size=5, replace=True)
# → [7, 7, 2, 9, 2]

# Chia train/test đúng cách
idx = np.arange(len(X))
rng.shuffle(idx)
train_idx = idx[:int(.8*len(idx))]
test_idx  = idx[int(.8*len(idx)):]
X_train, X_test = X[train_idx], X[test_idx]

**5. Giả lập dữ liệu thực tế**

Tạo dataset hoàn chỉnh để test model trước khi có dữ liệu thật — một kỹ năng cực kỳ quan trọng.

In [ ]:
rng = np.random.default_rng(42)
n = 500

# Dataset phân loại: 2 cụm điểm (classification)
X0 = rng.normal([2,2],  1.0, (n//2, 2))  # class 0
X1 = rng.normal([5,5],  1.2, (n//2, 2))  # class 1
X  = np.vstack([X0, X1])
y  = np.array([0]*(n//2) + [1]*(n//2))

# Dataset hồi quy: y = 2x + noise (regression)
x    = rng.uniform(0, 10, 300)
y_r  = 2*x + 1 + rng.normal(0, 2, 300)   # signal + noise

# Dữ liệu bán hàng có mùa vụ (time series)
t      = np.linspace(0, 2*np.pi, 365)
trend  = np.linspace(100, 150, 365)
season = 20 * np.sin(t)
noise  = rng.normal(0, 5, 365)
sales  = trend + season + noise